USE [master]
GO
/****** Object:  Database [testing]    Script Date: 27/04/2025 17:19:22 ******/
CREATE DATABASE [testing]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'testing', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\testing.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'testing_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\testing_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [testing] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [testing].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [testing] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [testing] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [testing] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [testing] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [testing] SET ARITHABORT OFF 
GO
ALTER DATABASE [testing] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [testing] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [testing] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [testing] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [testing] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [testing] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [testing] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [testing] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [testing] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [testing] SET  DISABLE_BROKER 
GO
ALTER DATABASE [testing] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [testing] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [testing] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [testing] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [testing] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [testing] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [testing] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [testing] SET RECOVERY FULL 
GO
ALTER DATABASE [testing] SET  MULTI_USER 
GO
ALTER DATABASE [testing] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [testing] SET DB_CHAINING OFF 
GO
ALTER DATABASE [testing] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [testing] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [testing] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [testing] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'testing', N'ON'
GO
ALTER DATABASE [testing] SET QUERY_STORE = ON
GO
ALTER DATABASE [testing] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [testing]
GO
/****** Object:  User [localsafril]    Script Date: 27/04/2025 17:19:22 ******/
CREATE USER [localsafril] FOR LOGIN [localsafril] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[MasterVehicle]    Script Date: 27/04/2025 17:19:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MasterVehicle](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[VehicleName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterVehicle] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MasterVehicleDetail]    Script Date: 27/04/2025 17:19:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MasterVehicleDetail](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[VehicleId] [int] NOT NULL,
	[VehicleDetailName] [nvarchar](255) NULL,
	[VehicleDescription] [nvarchar](max) NULL,
	[IsActive] [bit] NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedBy] [nvarchar](50) NULL,
	[UpdatedDate] [datetime] NULL,
	[UpdatedBy] [nvarchar](50) NULL,
 CONSTRAINT [PK_MasterVehicleDetail] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  View [dbo].[V_Vehicle]    Script Date: 27/04/2025 17:19:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[V_Vehicle] as
SELECT 
	A.id as VehicleId,
	B.Id as VehicleDetailId,
	A.VehicleName,
	B.VehicleDetailName,
	B.VehicleDescription,
	B.IsActive,
	B.CreatedBy,
	B.CreatedDate,
	B.UpdatedBy,
	B.UpdatedDate
FROM
	MasterVehicle A
LEFT JOIN 
	MasterVehicleDetail B ON B.VehicleId = A.Id
GO
/****** Object:  Table [dbo].[TestingName]    Script Date: 27/04/2025 17:19:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TestingName](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NULL,
	[IsActive] [nvarchar](1) NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[UpdatedDate] [datetime] NULL,
	[UpdatedBy] [nvarchar](100) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MasterVehicleDetail]  WITH CHECK ADD  CONSTRAINT [FK_MasterVehicleDetail_MasterVehicle] FOREIGN KEY([VehicleId])
REFERENCES [dbo].[MasterVehicle] ([Id])
GO
ALTER TABLE [dbo].[MasterVehicleDetail] CHECK CONSTRAINT [FK_MasterVehicleDetail_MasterVehicle]
GO
USE [master]
GO
ALTER DATABASE [testing] SET  READ_WRITE 
GO
